language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install -r <(cat requirements.txt requirements.test.txt)
# command to run tests
script:
  - pytest --version
  - pytest
branches:
  only:
    - master
    - develop
